---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  MY_SCHEMA: mydb
  SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false
  SPRING_DATASOURCE_USERNAME: root