---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MY_SCHEMA: mydb
  SPRING_DATASOURCE_URL: jdbc:mysql://{{ .Release.Name }}-db-service:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false
  SPRING_DATASOURCE_USERNAME: root