---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-helm.fullname" . }}
  labels:
    {{- include "hello-helm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hello-helm.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080